<?php

return [
    'apartment_features' => [
        'pet_policy' => [
            'p1' => 'Cats Allowed',
            'p2' => 'Dogs Allowed',
            'p3' => 'Pets Allowed',
            'p4' => 'Pets Not Allowed',
        ],

        'unit_features' => [
            'u1'  => 'Balcony',
            'u2'  => 'Dining Room',
            'u3'  => 'Dishwasher',
            'u4'  => 'Duplex',
            'u5'  => 'Eat In Kitchen',
            'u6'  => 'Fireplace',
            'u7'  => 'Furnished',
            'u8'  => 'Garden',
            'u9'  => 'Granite Kitchen',
            'u10' => 'Hardwood',
            'u11' => 'High Ceilings',
            'u12' => 'Laundry In Unit',
            'u13' => 'Light',
            'u14' => 'Loft',
            'u15' => 'Marble Bath',
            'u16' => 'Multi Level',
            'u17' => 'Outdoor Space',
            'u18' => 'Patio',
            'u19' => 'Private Deck',
            'u20' => 'Renovated',
            'u21' => 'Terrace',
            'u22' => 'Triplex',
            'u23' => 'Vacation Rental',
            'u24' => 'Walk-In Closet',
            'u25' => 'Walls OK',
        ],
    ],

    'building_features' => [
        'amenities' => [
            '0' => 'Bicycle Room',
            '1' => 'Brownstone',
            '2' => 'Business Center',
            '3' => 'Children Playroom',
            '4' => 'Common Outdoor Space',
            '5' => 'Concierge',
            '6' => 'Diplomats OK',
            '7' => 'Doorman',
            '8' => 'Elevator',
            '9' => 'Garage',
            '10' => 'Health Club',
            '11' => 'Laundry',
            '12' => 'Live In Super',
            '13' => 'Lounge',
            '14' => 'New Construction',
            '15' => 'Nursery',
            '16' => 'Pool',
            '17' => 'Receiving Room',
            '18' => 'Roof Deck',
            '19' => 'Storage',
            '20' => 'Subway',
            '21' => 'Valet',
            '22' => 'Virtual Doorman',
            '23' => 'Wheelchair Access',
            '24' => 'WiFi',
        ],
    ]
];
