<?php

return [
    "boro" => [
        1 => 'Manhattan',
        2 => 'Brooklyn',
        3 => 'Queens',
        4 => 'Bronx',
        5 => 'Staten Island',
        6 => 'Other'
    ],

    'neighborhoods' => [
        1 => [
            "Battery Park City",
            "Bowery",
            "Chinatown",
            "Civic Center",
            "East Village",
            "Financial District",
            "Greenwich Village",
            "Little Italy",
            "Lower East Side",
            "NoHo",
            "NoLita",
            "SoHo",
            "Tribeca",
            "Two Bridges",
            "West Village",
            "Chelsea",
            "Flatiron District",
            "Garment District",
            "Gramercy Park",
            "Hell's Kitchen",
            "Kips Bay",
            "Koreatown",
            "Midtown East",
            "Murray Hill",
            "NoMad",
            "Stuyvesant Town - Peter Cooper Village",
            "Theater District",
            "Central Harlem",
            "Central Park",
            "East Harlem",
            "Inwood",
            "Upper East Side",
            "Upper West Side",
            "Washington Heights",
            "West Harlem",
            "Randalls-Wards Island",
            "Roosevelt Island",
        ],

        2 => [
            "Bedford-Stuyvesant",
            "Bushwick",
            "Greenpoint",
            "Williamsburg",
            "Boerum Hill",
            "Carroll Gardens",
            "Cobble Hill",
            "Gowanus",
            "Greenwood Heights",
            "Park Slope",
            "Prospect Park",
            "Red Hook",
            "Sunset Park",
            "Windsor Terrace",
            "Crown Heights",
            "East Flatbush",
            "Flatbush",
            "Kensington",
            "Midwood",
            "Ocean Hill",
            "Brooklyn Heights",
            "Brooklyn Navy Yard",
            "Clinton Hill",
            "DUMBO",
            "Downtown Brooklyn",
            "Fort Greene",
            "Prospect Heights",
            "Vinegar Hill",
            "Bath Beach",
            "Bay Ridge",
            "Bensonhurst",
            "Borough Park",
            "Dyker Heights",
            "Mapleton",
            "Brighton Beach",
            "Coney Island",
            "Gravesend",
            "Sheepshead Bay",
            "Brownsville",
            "Canarsie",
            "Cypress Hills",
            "East New York",
            "Bergen Beach",
            "Flatlands",
            "Floyd Bennett Airfield",
            "Marine Park",
            "Mill Basin",
        ],

        3 => [
            "Astoria",
            "Corona",
            "East Elmhurst",
            "Elmhurst",
            "Forest Hills",
            "Glendale",
            "Jackson Heights",
            "Long Island City",
            "Maspeth",
            "Middle Village",
            "Rego Park",
            "Ridgewood",
            "Sunnyside",
            "Woodside",
            "Auburndale",
            "Bayside",
            "College Point",
            "Flushing",
            "Flushing Meadows-Corona Park",
            "Fresh Meadows",
            "Glen Oaks",
            "Kew Gardens",
            "Kew Gardens Hills",
            "Whitestone",
            "Briarwood",
            "Hollis",
            "Holliswood",
            "Jamaica",
            "Jamaica Estates",
            "Jamaica Hills",
            "South Jamaica",
            "St. Albans",
            "Forest Park",
            "Howard Beach",
            "Ozone Park",
            "Richmond Hill",
            "South Ozone Park",
            "Woodhaven",
            "Far Rockaway",
            "Rockaway Beac"
        ],

        4 => [
            "Bedford Park",
            "Belmont",
            "Bronx Park",
            "Concourse",
            "Concourse Village",
            "East Tremont",
            "Fordham Heights",
            "Fordham Manor",
            "Highbridge",
            "Hunts Point",
            "Kingsbridge",
            "Longwood",
            "Marble Hill",
            "Morris Heights",
            "Morrisania",
            "Mott Haven",
            "Mount Eden",
            "Mount Hope",
            "Norwood",
            "Riverdale",
            "University Heights",
            "Van Cortlandt Park",
            "West Farms",
            "Allerton",
            "Clason Point",
            "Morris Park",
            "Parkchester",
            "Pelham Bay",
            "Pelham Parkway",
            "Throgs Neck",
            "Unionport",
            "Van Nest",
            "Wakefield",
            "Westchester Village",
            "Williamsbridge",
            "Woodlawn Height"
        ],

        5 => [
            "East Shore",
            "Mid-Island",
            "North Shore",
            "South Shor"
        ]
    ]
];
